### ISSUE TITLE
Need a usable peer

### ISSUE THREAD

**Issue by panlilu** [maticnetwork/launch#12]
The list of seed nodes on README.md is empty.
I can't find any peers of Matic bor mainnet.

**Comment by loopersfriend** [comment]
Bump this. I can't get my nodes running without one.

**Comment by loopersfriend** [comment]
I got it use this:

seeds="f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656"

**Comment by panlilu** [comment]
> I got it use this:
> 
> seeds="f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656"

Not working for me.
I added this seeds to config file and the node is not syncing.
The default p2p port of  bor node is 30303 in the start.sh script but the port of seeds given is 26656.

**Comment by loopersfriend** [comment]
oh for the Bor... sorry I misread. Yeah I can't find a seed node for bor either. the ones in this doc don't seem to work https://docs.matic.network/docs/validate/counter-stake-stage-2/linux-validator-sentry-setup

**Comment by loopersfriend** [comment]
any luck? Seems like people want to keep the mainnet closed off to outsiders or just not support the community.

**Comment by loopersfriend** [comment]
ok mine works now! 
enode://cfacaa4008d512e1ab0352071a171e30d016fe0c4864554811b356403c51e9464f667d70db93053b23171fc73f9559bb1c5a19e57b1002ae2e1b50ae95dae750

**Comment by panlilu** [comment]
> ok mine works now!
> enode://cfacaa4008d512e1ab0352071a171e30d016fe0c4864554811b356403c51e9464f667d70db93053b23171fc73f9559bb1c5a19e57b1002ae2e1b50ae95dae750

Where is the @ip:port part?

**Comment by junnmm** [comment]
A simple workaround : just use the [bootnodes for ethereum mainnet](https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go#L25).  As  [ENR v4](https://github.com/ethereum/devp2p/blob/master/enr.md#record-structure) does not contain a chain ID, an ethereum mainnet node will also keep ENRs for other chains.

**Comment by payephyoeaung87** [comment]
0x017A1653c0cB7B561c50717336c1F7fd912ed310

**Comment by payephyoeaung87** [comment]
No, no, I want to support the community, but I also want to give a golden cookie if I have a itchy hand

**Comment by temaniarpit27** [comment]
Please contact official discord for more support if this is still relevant
