### ISSUE TITLE
Error on deploying matic/polygon full node

### ISSUE THREAD

**Issue by yieniggu** [maticnetwork/launch#22]
Hello, i've been following the binary guides stated in https://docs.matic.network/docs/validate/mainnet/validator-guide-binaries#setup-network-directories.

However i can't connect to any peer, im running a vm on aws with required ports enabled, but im getting this ouput all the time:

![image](https://user-images.githubusercontent.com/45997136/127235136-6036d688-61eb-4976-b9f7-893081d0f0b9.png)

Attached is the config.toml of the sentry node, my intention is to use it as a community RPC, but it hasnt worked. 

Also, this is the output of starting the heimdall-rest-server.service:
![image](https://user-images.githubusercontent.com/45997136/127235287-ddce80d5-02c1-487e-a75e-8b8009b67983.png)

And to check if heimdall synced, still got on catching_up:
`{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "c57994b0e6e02a500b2b4eb67359a50ef03f3513",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "heimdall-137",
      "version": "0.32.7",
      "channels": "4020212223303800",
      "moniker": "polygon-latam-sentry",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://127.0.0.1:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "",
      "latest_app_hash": "",
      "latest_block_height": "0",
      "latest_block_time": "1970-01-01T00:00:00Z",
      "catching_up": true
    },
    "validator_info": {
      "address": "5C97B6CDEE63E6DF24BC6F732D4F8D74BEF9E692",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "BLv4syQd0PdjeoM3MPUOaokPRq33S8Yarhu5IeWZ1d2RnQ/bzIjwLB1VC5PXFY5Rg8ZOhzM6GusFF8LoHpdDyP4="
      },
      "voting_power": "0"
    }
  }
}`

**Comment by ssandeep** [comment]
Please try the following:
```
sudo service heimdalld stop
mv ~/.heimdalld/config/addrbook.json ~/.heimdalld/config/addrbook.json_bkp
sudo service heimdalld start
```
