### ISSUE TITLE
Fatal: invalid genesis file: json: cannot unmarshal object into Go struct field BorConfig.config.bor.period of type uint64

### ISSUE THREAD

**Issue by MrAbaddon** [maticnetwork/launch#37]
The bor mombai genesis file is invalid.
Tried with testnet-v4/without-sentry/bor/genesis.json and testnet-v4/sentry/sentry/bor/genesis.json
When I initiate bot:

`bor --datadir ./bor init ./bor/genesis.json` 

I get an error:

`Fatal: invalid genesis file: json: cannot unmarshal object into Go struct field BorConfig.config.bor.period of type uint64`

**Comment by ngoisaoquay** [comment]
> The bor mombai genesis file is invalid. Tried with testnet-v4/without-sentry/bor/genesis.json and testnet-v4/sentry/sentry/bor/genesis.json When I initiate bot:
> 
> `bor --datadir ./bor init ./bor/genesis.json`
> 
> I get an error:
> 
> `Fatal: invalid genesis file: json: cannot unmarshal object into Go struct field BorConfig.config.bor.period of type uint64`

I get the same error when run from docker. Did you resolve this error?

**Comment by MrAbaddon** [comment]
Yes. I've checked the mainnet scheme and copied the 2 lines that give error.
Line 17: changed to "period": 2,
Line 22: changed to "backupMultiplier": 2,

**Comment by ngoisaoquay** [comment]
> Yes. I've checked the mainnet scheme and copied the 2 lines that give error. Line 17: changed to "period": 2, Line 22: changed to "backupMultiplier": 2,

Thank you so much, I can start it.

**Comment by ngoisaoquay** [comment]
> Yes. I've checked the mainnet scheme and copied the 2 lines that give error.
> Line 17: changed to "period": 2,
> Line 22: changed to "backupMultiplier": 2,

Hi Mrabaddon, can you share me how can you run it? I tried start it with docker compose but it can not sync after few minutes

**Comment by sballmer** [comment]
Got the same error on the mumbai testnetwork, was fixed using the latest version of the genesis.json file **and** the latest version of bor.

**Comment by hiteshSharma6** [comment]
Getting the same error on using the latest genesis.json file which was updated yesterday.

**Comment by GPrendi30** [comment]
I had the same problem, I fixed it:
"period": 2,
"backupMultiplier": 2,

**Comment by vcastellm** [comment]
As @sballmer said, you need to use the latest `bor` version together with the latest genesis version.
