### ISSUE TITLE
Polygon is targeting ~7.5-10M avg block gas usage post-London HF

### ISSUE THREAD

**Issue by zhongfu** [maticnetwork/launch#42]
After the London HF block, validators will begin to target an average block gas usage of `parent.gasLimit / elasticityMultiplier`. `elasticityMultiplier` is set to `2`, so the base fee will scale accordingly in order to achieve an average block gas usage of 1/2 of the gas limit.

I'm guessing this effect (of... effectively decreasing tx throughput by ~half) isn't actually intended, but that's what's actually happening now. If that's the case, it'll probably be a good idea to update the bor `start.sh` scripts to reflect a block gas limit that's 2x as high as the intended average block gas usage to maintain the pre-London HF average block gas usage *and* tell validators to update their configs

Kind of tangential to the topic, but `miner.gasPrice` refers to minimum *effective tip* instead of minimum gasPrice after the London HF (i.e. EIP-1559 txes must have priorityFee set to at least 30 gwei and legacy txes must have a gasPrice that's at least `baseFee + 30 gwei`), so it might be a good idea to update documentation to highlight this change

**Comment by temaniarpit27** [comment]
Please check the latest changes and reopen if required
