### ISSUE TITLE
The synchronization of the bor node is always about 100 blocks away from the latest height

### ISSUE THREAD

**Issue by summerxue1992** [maticnetwork/launch#43]
eth_syncing return:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/35830823/153815516-768c766c-a7a7-4c5d-8fb9-ad95f9f1586f.png">

eth_blockNumber   return:
<img width="172" alt="image" src="https://user-images.githubusercontent.com/35830823/153815678-23fb9f3a-c48c-41a7-b98c-e5341587f901.png">

The node I started with docker, heimdall image version: 0.2.4, bor image version: 0.2.14

**Comment by 0xKrishna** [comment]
What's your config?
Looks like you are using `snap` mode which we don't support on mainnet as of now, Please only use `full` mode.
