### ISSUE TITLE
Please update start.sh for the London fork

### ISSUE THREAD

**Issue by EthanScully** [maticnetwork/launch#45]
The gasprice needs to go back to 1 gwei, gas limit needs to be doubled, and gas target should be removed.

**Comment by DevSamral** [comment]
> The gasprice needs to go back to 1 gwei, gas limit needs to be doubled, and gas target should be removed.
> 
> 

Hello @ A support ticket has been opened for you. Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.com/)

**Comment by temaniarpit27** [comment]
Please check the latest changes and reopen if required
