### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by 0xRook1e** [maticnetwork/launch#53]
docker compose -f matic-sentry-without-snapshotting.yml --env-file mumbai.env up
[+] Running 2/0
 ⠿ Container bor0       Created                                                                                                                                           0.0s
 ⠿ Container heimdall0  Created                                                                                                                                           0.0s
Attaching to bor0, heimdall0
bor0       | sh: syntax error: unexpected "&&"
heimdall0  | {
heimdall0  |   "chain_id": "heimdall-80001",
heimdall0  |   "node_id": "7c634915bde183065f883819a8a1756118dca7a2"
heimdall0  | }
heimdall0  | bash: -c: line 3: syntax error near unexpected token `&&'
heimdall0  | bash: -c: line 3: `  && wget -O /root/.heimdalld/config/genesis.json https://raw.githubusercontent.com/maticnetwork/launch/master/testnet-v4/sentry/sentry/heimdall/config/genesis.json -P /root/.heimdalld/config  '
bor0 exited with code 2
heimdall0 exited with code 2

**Comment by temaniarpit27** [comment]
Please check the latest changes and reopen if required
