### ISSUE TITLE
Please use tags to version this repo

### ISSUE THREAD

**Issue by danielkokobt** [maticnetwork/launch#71]
The recommended version of bor or heimdall is usually not the latest one, but this repo is usually updated to match the latest release. If I want to install a version of bor or heimdall that is older than the latest, I have no way of knowing which commit to check out from this repo.

To solve this problem, you can simply tag commits with the bor and heimdall release that they correspond to.  For example the latest commit (as of today) could be tagged with both `bor-0.3.7` and `heimdall-0.3.3`

**Comment by pratikspatil024** [comment]
Hi @danielkokobt thanks for the suggestion, and sorry to keep you waiting.
Starting bor version 0.3.0 onwards, we have moved the config files and relevant files to the bor repo itself see [here](https://github.com/maticnetwork/bor/tree/develop/packaging/templates). Recommend you checking these there, thanks!
